### ISSUE TITLE
Way to support multiple GraphQl schema/Urls

### ISSUE THREAD

**Issue by akkikumar72** [magidoc-org/magidoc#162]
### Describe the problem

Will be good to support multiple graphQl endpoints

### Describe the proposed solution

Is there a possibility to support multiple graphQl Urls.
something like
```
introspection: {
    type: 'url',
    url: ['www.graphQlendpoint.com/url1','www.graphQlendpoint.com/url2','www.graphQlendpoint.com/url3' ],
    headers: {
    },
  },
```

This will generate output for all 3 urls inside output directory

### Importance

Would make my life easier

**Comment by pelletier197** [comment]
Thank you for raising this issue. 

I understand what you are asking for, but I must admit, I have a little difficulty to seize what is the goal you want to achieve with this feature. 

1. Do you wish to generate 3 websites at once? How would Magidoc link these 3 websites together?

2. You marked this as `Would make my life easier`. 
    - Have you explored an alternative to the proposed solution?
    - If yes, what is the problem with the alternative?

Depending on what you want to do, there may already be a way to implement it with the existing set of features. If not, I'll be happy to implement something to help you reach your goal!

**Comment by akkikumar72** [comment]
Thanks for reply.

1. I was thinking to have something like 
```
docs/—
      |
      url1/-
        |     |
        |      index.html & other files
     url2/-
        |     |
        |      index.html & other files
     url3/-
        |     |
        |      index.html & other files
```

Then by running any static server inside docs. Will create those urls.

2. I tried some shell scripts alternatives, but that doesn't worked in every local devices. 

Any alternative solution from this library will be very nice.

**Comment by pelletier197** [comment]
Okay, thank you for the details. I think there is a way to accomplish what you want to do with the current feature set offered. 

It could be achieve by calling magidoc cli 3 times with an environment variable to provide an URL and an output build folder. I think this could also be achieved with a javascript script rather then a shell script, which would make it cross platform.

Magidoc also already has a caching mechanism in place when building the same template multiple times in a row, so that would give you almost the same speed than what you propose.

If I have time today, I will write an example of how to do that and you can let me know what you think of the solution. 

> For the record, I am pushing a little back on your solution, because implementing it would be more complicated than it seems. You would need to provide the output folder path for each introspection query. And there would need to be a redirect from the root path to one the schema's website. So that would imply a lot of changes and that would potentially not do what every user may want. So doing it with a custom script allows to let everyone decide on what they want specifically, while keeping Magidoc's configuration simple.

**Comment by akkikumar72** [comment]
I will really appreciated an  sample example.

**Comment by pelletier197** [comment]
I implemented an example of a multi-schema website, which is available [here](https://github.com/magidoc-org/magidoc/tree/main/packages/examples/multi-schema). Let me know if this solves your problem.

**Comment by akkikumar72** [comment]
@pelletier197 This is perfect, what I was looking for. Really appreciated 🙌🏽

**Comment by pelletier197** [comment]
Happy to know it 🙂 enjoy!
