### ISSUE TITLE
Host on Azure storage account static website

### ISSUE THREAD

**Issue by DerekJDev** [magidoc-org/magidoc#178]
I'm trying to host the static website on a storage account in Azure. Due to the clean URLs I'm not able to get the pages to load. In the static website settings, I'm able to specify the index document (index.html), but when it does it's refresh from the meta tag to /introduction/welcome it's saying that it can't find the welcome html doc.

Has anyone set this up in the same type of environment? If so, how did you get it to work? I'm assuming there is a way since it's supported in AWS, but that's just an assumption. Thanks in advance.

Here's the docs I've been referencing: https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?source=recommendations&tabs=azure-portal

**Comment by pelletier197** [comment]
Hi @DerekJDev. I have never tried deploying in Azure. I will give it a try as soon as posskblr and come back to you.

**Comment by DerekJDev** [comment]
Hi @pelletier197 I appreciate you looking into this! At least I know I wasn't missing something really obvious that needed to be changed 😄! 

I'm going to look into using an Azure Static Web App instead of a static website in a storage account and see if I have any luck there.  I will be sure to keep you updated and I'd be glad to document it if I get it to work.

Thanks again for the help!

**Comment by DerekJDev** [comment]
Hey @pelletier197 !

Quick update, I got it to work using an Azure Static Web App. The only problem is that they limit the app files to 500MB and due to the size of our API we surpass that limit... So we decided to move over to GitHub pages.

With that, I have everything committed to our GitHub repo, but I'm still getting a 404 saying that it can find the requested file.

Here's the magidoc.mjs file:
```
function markdown(string) {
  // Takes the first indent and trims that length from everywhere.
  // Markdown templates don't like the extra space at the beginning.
  const target = string[0];
  const trimSize = /^\s+/.exec(string)[0].length;
  return target
    .split('\n')
    .map((line) => line.substr(trimSize - 1))
    .join('\n');
}

export default {
  introspection: {
    type: 'sdl',
    paths: ['./schema.graphql'],
  },
  website: {
    template: 'carbon-multi-page',
    staticAssets: '../source/repos/api-reference/assets',
    output: '../source/repos/api-reference',
    options: {
      siteRoot: '/TarventInc/api-reference',
      appTitle: 'Tarvent API',
      appLogo: 'https://cdn.trvt.io/resource/graphics/logo/RefLogo.png',
      appFavicon: 'https://cdn.trvt.io/resource/graphics/logo/favicon-16x16.png',
      
      pages: [
        {
          title: 'Welcome',
          content: markdown`
            # 👋 Hi

            Welcome to [Tarvent](https://api.tarvent.com/graphql/)'s GraphQL documentation!
          `,
        },
      ],
      externalLinks: [
        {
          href: 'https://api.tarvent.com',
          label: 'Tarvent API',
          kind: 'Tarvent',
        },
        {
          href: 'https://www.tarvent.com/contact-us',
          label: 'Tarvent support',
          kind: 'Tarvent',
        },
      ],
      queryGenerationFactories: {
        UUID: '000000000000000000',
        Byte: '000000',
        Decimal: 0.0,
        'Int!': 420,
        String: 'abc',
      },
    },
  },
};
```

Does anything seem off in here? 

Here's the URL to the docs: https://developer.tarvent.com
Here's the URL to the repo: https://github.com/TarventInc/api-reference

Thanks again!

**Comment by pelletier197** [comment]
Hi @DerekJDev. Thanks for the update. Would you be willing to document your procedure for azure even if you won't be using it. Just for reference for future users. That would be awesome!

About your website, seems to me like you should remove the `siteRoot`. Since you used a custom domain and your documentation is hosted at the root of your url. The site root would be necessary if you didn't have a custom domain. Let me know if this works. L

**Comment by DerekJDev** [comment]
@pelletier197 That worked! I can add to the documentation this weekend most likely... Currently very busy at work, but I'd be glad to help as soon as I have time.
