### ISSUE TITLE
Sort arguments as default - Not alphabetically

### ISSUE THREAD

**Issue by Krato** [magidoc-org/magidoc#189]
### Describe the problem

Hi! First thank you for this project 😄 

I want to know if is possible to show the arguments/keys as found on the schemas and not alphabetically. 

### Describe the proposed solution

If there's no option now, will be great to do it in future cause sometimes is hard to find the arguments or the keys in a buch of objects that are not matching your schema order.

Thank you!

### Importance

Nice to have

**Comment by pelletier197** [comment]
Hi @Krato. Thank you for your suggestion. 

Yes, it would be possible quite easily. I could probably also change argument order to the schema one by default. There's not really any good reason to sort alphabetically by default. 

The configuration could look something like 

```js
{
  website: {
    options: {
       argumentSorting: 'default' | 'alphabetically'
    }
  }
}
```

Would that fit your needs ?

**Comment by Krato** [comment]
Hi @pelletier197 

Yes, that way it would be configurable and easy to implement.

On the other hand setting it to default without sorting seems fine to me. But that's up to you. 

As long as there is the option to change it I think it would be good to add it.

Thanks!

**Comment by Krato** [comment]
Ahh, and will be greate to be implemented, not just in arguments. Also in Type fields for example.

Just as a suggestion 😅

**Comment by pelletier197** [comment]
@Krato when you say field, if by fields you mean this:

![image](https://user-images.githubusercontent.com/24528884/221416338-b01b780b-08a3-4e39-bd44-f3c71b10b31c.png)

then is it possible. I'll do it at the same time.
