### ISSUE TITLE
Ruby Syntax Highlighting from Prism not being applied

### ISSUE THREAD

**Issue by jonny-ras** [magidoc-org/magidoc#195]
### Describe the bug

I've some Ruby code that isn't being highlighted, you can see the example here:

https://developers.rasayel.io/useful-scripts/exporting-all-conversations

I'm not familiar with Svelte or Prism, but I suspect it just needs to be added as a [dependency here](https://github.com/magidoc-org/magidoc/blob/0e57d4e57e89b34436fd53b904ec26ad2693bf18/packages/starters/carbon-multi-page/src/routes/%2Blayout.svelte)?

### Reproduction

Just add some code to a document, try to add Ruby syntax highlighting to it:

```ruby
def some_ruby
  puts "This is not highlighted properly"
end
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 134.08 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 16.2
```
```


### Severity

Annoyance

**Comment by pelletier197** [comment]
Hi. Yes, you're right, the language import is missing in the file you pointed. To keep the website lightweight, we import only the most popular languages, and it seems I missed Ruby. Would you be interested in opening a small PR to add it? I'll deploy it right away!

**Comment by jonny-ras** [comment]
@pelletier197 that would be amazing, thank you! I'll open it up right now

**Comment by jonny-ras** [comment]
@pelletier197 https://github.com/magidoc-org/magidoc/pull/196

Thanks for getting back to me - this should cover it, I believe!

**Comment by pelletier197** [comment]
@jonny-ras This is released! Thank you for using Magidoc. I'm happy to see you're using almost all the features available, that's awesome. 

As a tip for your documentation, I see that you're using a few images. If you're interested, there is a way to make these images a bit more appealing. For instance [Open Collective's API documentation](https://graphql-docs-v2.opencollective.com/access) uses images as well. 

This is achieved using raw HTML in the markdown. See how we did [here](https://github.com/opencollective/graphql-docs-v2/blob/main/magidoc/pages/02.Access.md?plain=1). This way, you could add a bit of spacing around them or center them if you want :wink:

**Comment by jonny-ras** [comment]
@pelletier197 thank you! I absolutely love this tool. I tried a bunch and this was by far the simplest.

Couldn't figure out the images myself so that is - _super_ helpful. I hated that we couldn't center them! 😂 Will make that change ASAP!

One feature request, I'd love to be able to change the height of the query field. All our types are under `app` so the query is pretty, and fixing the height makes it quite tricky to see easily. 

I might open a PR for that at some point to make it an optional setting, if you're open to the idea.

**Comment by pelletier197** [comment]
> One feature request, I'd love to be able to change the height of the query field.

I'm not sure I understand what you mean. But you can open a feature request if you want to provide more details. Always happy to get some contribution!
