### ISSUE TITLE
Example body has a fixed max-height, meaning queries with a lot of possible fields are hard to easily parse visually

### ISSUE THREAD

**Issue by jonny-ras** [magidoc-org/magidoc#197]
### Describe the problem

At Rasayel.io we use the `app` concept as our base query. Everything is done through an `app`, and so our main query point will always look something like
```gql
query GetSomeData {
  app {
    conversations {
     ...
    }
  }
}
```

This works great in practice, however in the Queries section of our documentation, the fixed height / width of the example field makes it difficult to drill into
![image](https://user-images.githubusercontent.com/102602123/222954315-333257c9-7d5b-4e0a-9e5d-aa7c1eedeca5.png)
![2023-03-05 11 12 50](https://user-images.githubusercontent.com/102602123/222954329-7abafbf0-bbd9-4159-9df5-3f281683ad5d.gif)

We won't be changing the base query of the system any time soon, everything will always go through app.

Looking at the example field, you can see it has a fixed max-height set directly on the query body

![image](https://user-images.githubusercontent.com/102602123/222954406-5fb61ae4-3e49-4a69-8179-c380eededb88.png)

I've tried finding where this is set in the codebase but I can't find it.

### Describe the proposed solution

I would like this to be configurable on an app level, I'm fine with displaying a larger query field if it means there's less scrolling required for our users!

You can check out how difficult it is to use here: https://developers.rasayel.io/queries/app

### Importance

Would make my life easier

**Comment by pelletier197** [comment]
This should now be possible with the latest release. See the `customStyles` property inside the website configuration. https://magidoc.js.org/cli/magidoc-configuration

Example of CSS would be 

```css
.code-container {
    max-height: fit-content !important;
}
```

Unfortunately, the import is required to override some of the CSS of the website, but it works. :smiley: Let me know if you need anything else!

**Comment by jonny-ras** [comment]
Wow thank you @pelletier197 amazing! 🎉
