### ISSUE TITLE
Overriding template CSS with custom styles

### ISSUE THREAD

**Issue by amanb014** [magidoc-org/magidoc#201]
### Describe the problem

I am trying to update some styles of the template that gets generated by the web page. I think having a stylesheet that gets imported on the header with custom styles would be a great. I can see that magidoc already supports moving static assets to the website root.

Though I can see that there is no way to update the HTML files that are generated to import these assets in the header or anywhere else (other than the app logo and favicon).

## Solution 1 (preferred): Static CSS files in all HTML headers
Add a static css file like so:
`/static/styles/custom-styles.css`

Then, have a property in the `magidoc.mjs` file to have styles get imported in the HTML:
```
module.exports = {
  ...
  website: {
    customStyleSheets: ['styles/custom-styles.css']
  }
}
```

This can maybe be even more generic to add anything to `<head>`

## Solution 2: Just paste Custom styles in a style tag in the HTML
```
module.exports = {
  website: {
    customStyles: `
      .overrideClass {
        color: "#e3e3e3"
      }
    `,
  }
}
```

The contents of `customStyles` then just get added to the HTML header in a `<style>` tag.

### Importance

Nice to have

**Comment by amanb014** [comment]
Just for my own notes, seems like this can be added somewhere here:
https://github.com/magidoc-org/magidoc/blob/main/packages/starters/carbon-multi-page/src/routes/%2Blayout.svelte#L64-L66

After adding the option to config (not sure how, yet).

**Comment by pelletier197** [comment]
I didn't get an answer from you, but I added the feature as described here since I had some time today. Let me know what you think :smile:

**Comment by amanb014** [comment]
This works great, thanks so much for the quick implementation! Sorry about the late response here, but I think this is exactly what I needed :)
