### ISSUE TITLE
Fetch @magidoc/starter-carbon-multi-page From NPM Registry

### ISSUE THREAD

**Issue by teganfleishman** [magidoc-org/magidoc#307]
### Describe the problem

Currently the carbon multi-page template is fetched from a zip file in GitHub, which causes the template generation step to fail in cases where GitHub is not authorized for use.

### Describe the proposed solution

Instead, it would be great to register `@magidoc/starter-carbon-multi-page` with NPM and import the template directly from NPM instead of GitHub.

### Importance

I cannot use Magidoc without it

**Comment by pelletier197** [comment]
Hey, sorry for the late reply. I would have to look into if this is even possible. As an alternative at the moment, you could use `magidoc eject` and have the template copied locally. https://magidoc.js.org/cli/command-eject. This allows for further customization as well. 

What I believe might be a possible way to do would be to support URLs for `template` field. This way you could host the template wherever you want and fetch it from there. But I'm not sure npmjs supports hosting templates the way its done. Basically, it needs an URL to fetch the template from, and that URL must download a zip of the template.
