### ISSUE TITLE
Command line parameter to specify .mjs file

### ISSUE THREAD

**Issue by TomHAnderson** [magidoc-org/magidoc#344]
### Describe the problem

I like that this can be used to generate documentation as we see on the magidoc home page.  I would like to store two `magidoc.mjs` files in the same directory as `graphql.mjs` and `docs.mjs`.  

### Describe the proposed solution

I feel the hard-coded `magidoc.mjs` needs to be changed to allow a `magidoc generate --config=docs.mjs`

### Importance

Nice to have

**Comment by pelletier197** [comment]
Hi, this is already possible. Although the name of the parameter is `--file`, not `--config`. 

You can find more with `magidoc generate --help`. 

Let me know if this solves your problem.
