### ISSUE TITLE
Getting random value for scalar errors after upgrading from 5.0.3 to 6.0.1.

### ISSUE THREAD

**Issue by aowen-dotmatics** [magidoc-org/magidoc#401]
### Describe the bug

After upgrading from 5.0.3 to 6.0.1 the same GraphQL query now generates this error for multiple types:
```
Error: Cannot generate a random value for scalar '<type>'.
```
I can resolve the individual issues for each type with `queryGenerationFactories` in the config, but going back to 5.0.3 resolves the issue completely. Suspect this might be a regression.

### Reproduction

[application-version-id.graphql.zip](https://github.com/user-attachments/files/16728985/application-version-id.graphql.zip)

### Logs

```shell
node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
Error: 
Cannot generate a random value for scalar 'applicationId'. 
The random generator is not able to randomly generate a value for non-standard GraphQL scalars. 
You have to provide a custom factory by providing this in your magidoc config:
{
  website: {
    options: {
      queryGenerationFactories: {
        'applicationId': '<an-example-of-scalar-value>'
      }
    }
  }
}

To learn more about how to generate a custom scalar value, see: https://magidoc.js.org/cli/magidoc-configuration#querygenerationfactories

    at generateQuery (file:///tmp/carbon-multi-page@6.0.1/.svelte-kit/output/server/chunks/FieldDetails.js:218:13)
    at async Object.setField (file:///tmp/carbon-multi-page@6.0.1/.svelte-kit/output/server/chunks/FieldDetails.js:266:23)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)

Node.js v20.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
Running on a GitHub Ubuntu x64 hosted runner.

  Binaries:
    Node: 20.16.0
    npm:  10.8.1
    pnpm: 8.15.9
```

### Severity

Blocking an upgrade

**Comment by pelletier197** [comment]
Hi. It seems to me like this was the original intended behaviour. There was a bug in version 5 that caused the generation to succeed when it should have failed. 

This is important to ensure the documentation remains relevant. You should provide an scalar example for each of your type. Hope this helps. Let me know if you have any concerns about this.

**Comment by aowen-dotmatics** [comment]
That makes sense. But I assume this means I need to specify each endpoint in the config. I've looked at the docs and I see I need to do this:
```
  website: {
    options: {
      queryGenerationFactories:
```
But I'm the doc guy and I'm new to GraphQL so a more detailed example of how to create an example would be helpful.
