### ISSUE TITLE
Reading configuration file in Windows

### ISSUE THREAD

**Issue by kaleabmelkie** [magidoc-org/magidoc#67]
Following the basic steps from the [Getting Started section of the docs](https://magidoc-org.github.io/magidoc/introduction/get-started) errors with the following message on Windows when trying to run `generate`:

```
> npx @magidoc/cli@latest generate
Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```

---

My "magidoc.mjs" file:

```js
export default {
  introspection: {
    type: "url",
    url: "https://graphiql-test.netlify.app/.netlify/functions/schema-demo",
  },
  website: {
    template: "carbon-multi-page",
  },
};
```

**Comment by pelletier197** [comment]
Hi, thanks for raising the issue. 

Could you tell me what version of NodeJS you are on?  Also, could provide me with the output of running:

```
 npx @magidoc/cli@latest generate --stacktrace
```

Thanks in advance! 

I see that the issue was raised by many people on different projects. I will hop on my windows machine today and try to reproduce this issue.

**Comment by kaleabmelkie** [comment]
The stack trace has the same exact output:

![Uploading image.png…]()

I'm on Node.js v16.15.0 and npm v8.9.0

**Comment by pelletier197** [comment]
I closed this issue. It seems good to me. I get another issue with the deployed version related to peer dependencies. I'll open another issue for it. Thanks for raising the issue. I'll need to improve testing on Windows.
