### ISSUE TITLE
Add support for default Hasura types

### ISSUE THREAD

**Issue by pelletier197** [magidoc-org/magidoc#93]
Default Hasura types should be supported by query generation factories by default

```javascript
    {
        _text: "loremipsum",
        bigint: 1000,
        date: "2022-03-06T08:23:45.000Z",
        float8: 0.1,
        geography: { type: "Point", coordinates: [0, 0] },
        geometry: { type: "Point", coordinates: [0, 0] },
        jsonb: {},
        numeric: 1,
        smallint: 42,
        timestamp: "2022-03-06T08:23:45.000Z",
        timestamptz: "2022-03-06T08:23:45.000Z",
        uuid: "a12ce80c-42e3-4149-89cc-4afda30e5e7f",
      }
```

See #92 for more details.

**Comment by pelletier197** [comment]
Looking at [Hasura types](https://hasura.io/docs/latest/graphql/core/databases/postgres/postgresql-types/#types-table), some of the example here seem inacurate. For example, `bigint` seems to be a string. Would need to double check these.

**Comment by efstathiosntonas** [comment]
@pelletier197 you're right but the query accepts both integer and string as a value

this will work: 

```graphql
query MyQuery($total_likes: bigint = 3) {
  comment(where: {total_comment_likes: {_gte: $total_likes}}) {
    author_id
  }
}
```

also this does work: 

```graphql
query MyQuery($total_likes: bigint = "3") {
  comment(where: {total_comment_likes: {_gte: $total_likes}}) {
    author_id
  }
}
```

Hasura has some weird types but we should stick with their docs, we should treat `binint` as a `String`.

**Comment by pelletier197** [comment]
Alright. I'll be honest though, it' s a little weird to implement some of these types as string. For instance, another user could have a `bigint` type, and it would be more reasonable for this user to use a number as input. 

I think it makes sense to implement some of these with a natural default value.

```
        _text: "loremipsum",
        bigint: 1000000,
        float8: 0.1,
        numeric: 1,
        smallint: 42,
        timestamp: "2022-03-06T08:23:45.000",
        timestamptz: "2022-03-06T08:23:45.000Z",
        uuid: "a12ce80c-42e3-4149-89cc-4afda30e5e7f",
        jsonb: {}
        date: "1996-03-05"
```

However, some of these make less sense: 
- `geometry`, `geography` are two objects that could perfectly exist in any other API and look totally different.
- `jsonb` is super specific to Postgres, but might be okay to add
- `date` should be only yyyy-dd-mm (and that's also what Hasura returns anyways).

So I would implement all of these using the natural way if you're fine with it. If the type is ever not like you'd want too, you can always override it.

**Comment by efstathiosntonas** [comment]
Yeah, seems totally fair!
